name: Padavan

on: push

jobs:

  build_Padavan:

    name: 初始环境

    runs-on: ubuntu-latest

    steps:

      - name: 准备环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
          sudo -E apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot cpio git python-docutils gettext automake autopoint texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev
          sudo -E chmod 777 /opt

      - name: 更新资源
        run: |
          git clone --depth=1 https://github.com/ooairco/rt-n56u /opt/rt-n56u
          
      - name: 准备工具
        run: |
          cd /opt/rt-n56u/toolchain-mipsel
          sudo ln -sf /usr/bin/gcc-8 /usr/local/bin/gcc
          sudo ln -sf /usr/bin/g++-8 /usr/local/bin/g++
          ./clean_toolchain
          ./build_toolchain
          
          
      - name: 开始编译
        run: |
          cd /opt/rt-n56u/trunk
          ./clear_tree
          fakeroot ./build_firmware_modify NEWIFI3
      
      - name: 上传文件
        uses: actions/upload-artifact@master
        with:
          name: Padavan Firmware
          path: /opt/rt-n56u/trunk/images/
